### ISSUE TITLE
最近打开stl格式文件，只能看到一片空白

### ISSUE THREAD

**Issue by octifor** [ccseer/Seer-3D-Viewer#4]
最近使用seer预览.stl格式文件显示一片空白。如下图：
![image](https://user-images.githubusercontent.com/30651230/203901964-65b8af48-9d76-48b8-84fc-a9122a48f5cb.png)
使用其它软件（CAD Assistant）打开图档是可以看的
![image](https://user-images.githubusercontent.com/30651230/203902369-ba66be3c-4efb-44a9-9903-6a68b3928085.png)
电脑系统为Win11 22H2
软件版本为3.0.1 uwp版

**Comment by ccseer** [comment]
最近是以前可以预览的意思吗

**Comment by octifor** [comment]
具体从什么时间开始不能预览不太记得了，但是刚买这个软件并安装使用的时候是可以的（大概今年十月底十一月初的样子）。

**Comment by ccseer** [comment]
都是单机的, 以前能看现在不能看 估计是系统环境有啥变化.

可能以后会换一个 看 3D 文件方式, 目前就这样吧.
